Add wk2 note and media file
ekumenlabs/training_notes_gazebo_ros_2019 pull request #10
Opened 2019-09-11 14:14 UTC by stevendes

Adding the files of the wk2 in another PR

2019-09-11 14:18 UTC, stevendes commented
It doesn't allow me to choose the Reviewers, it just says "No reviews"

2019-09-11 14:22 UTC, eborghi10 commented
@stevendes check that you pushed changes from week 1.

2019-09-11 14:42 UTC, stevendes commented
So I need to remove the files from week 1 in order to proper push?

2019-09-11 15:13 UTC, ernestmc commented
> So I need to remove the files from week 1 in order to proper push?

Yes. For week 2 we only want to add the files that correspond to this week. The files for week 1 will be added in the other pull-request.

2019-09-11 17:31 UTC, eborghi10 commented
> So I need to remove the files from week 1 in order to proper push?

I assume you forgot to update this branch with your changes in master. Let's talk about this during today's meeting. Could you remind me, @stevendes ?

2019-09-11 17:36 UTC, stevendes commented
Yes, I will!

2019-09-11 17:48 UTC, eborghi10 requested changes
First pass done, PTAL.

2019-09-11 17:48 UTC, eborghi10 commented on milner_desvars/ros-notes.md
> +Graph Resource Names provide a hierarchical naming structure that is used for all resources in a ROS Computation Graph, such as Nodes, Parameters, Topics, and Services. These names are very powerful
Don't copy-paste long texts. Try to use your own words.

2019-09-11 17:48 UTC, eborghi10 commented on milner_desvars/ros-notes.md
> +Names are resolved relatively, so resources do not need to be aware of which namespace they are in. This simplifies programming as nodes that work together can be written as if they are all in the to
Again, instead of single quotes use inverted code to format code.

2019-09-11 17:48 UTC, eborghi10 commented on milner_desvars/ros-notes.md
> +Published topics:
The provided examples must be done using the simulator, not the Wiki.

2019-09-11 17:48 UTC, eborghi10 commented on milner_desvars/ros-notes.md
> +* Nodes
Use headers. Apply them to topics and parameters sever too.

2019-09-11 17:48 UTC, eborghi10 commented on milner_desvars/ros-notes.md
> +`$ rosparam list`
Wrong formatting.

2019-09-11 17:48 UTC, eborghi10 commented on milner_desvars/ros-notes.md
> +`$ rosparam list`
Also, for terminal commands, when you use `$` is because you're going to print an output. In this case, it's not necessary.

2019-09-11 17:48 UTC, eborghi10 commented on milner_desvars/ros-notes.md
> +3. Run the teleop
Use headers for this too.

2019-09-11 17:48 UTC, eborghi10 commented on milner_desvars/ros-notes.md
> +We would choose the topic `/clock`
Clock is not the best option. Use a sensor instead.

2019-09-11 17:48 UTC, eborghi10 commented on milner_desvars/ros-notes.md
> +![rqt_graph](media/rqtpic1.png)
In `rqt_graph` you have the option to print topics too. Please, replace the images to show both.

2019-09-11 17:48 UTC, eborghi10 commented on milner_desvars/ros-notes.md
> +As we can see, we have 4 nodes active, which are the ones that we found when running `rosnode list`.
I'm seeing 5 nodes in the graph. Why?

2019-09-11 17:48 UTC, eborghi10 commented on milner_desvars/ros-notes.md
> +* A slave API. The slave API is an XMLRPC API that has two roles: receiving callbacks from the Master, and negotiating connections with other nodes. For a detailed API listing, please see Slave API.
IMO don't put too much text but use your **own** words.

2019-09-13 18:28 UTC, stevendes commented
Ready for review

2019-09-13 20:40 UTC, eborghi10 approved these changes
LGMT!

2019-09-18 17:34 UTC, merged