Added third week's .md file about debbuging
ekumenlabs/training_notes_gazebo_ros_2019 pull request #15
Opened 2019-09-19 17:48 UTC by LucasJSch

# Ready for review

2019-09-19 20:00 UTC, eborghi10 commented on lucas_scheinkerman/Debugging_and_profiling_in_ROS.md
> +This text is the normal initial printing of `gdb`, except for the "no debugging symbols found" part. This is related to the fact that we didn't compile with the `DCMAKE_BUILD_TYPE=Debug` flag. **What
I recommend you to compile with this flag instead: `RelWithDebInfo`.

2019-09-19 20:05 UTC, eborghi10 requested changes
I made some comments, PTAL.

2019-09-19 20:05 UTC, eborghi10 commented on lucas_scheinkerman/Debugging_and_profiling_in_ROS.md
> +It can be seen that the `.cpp` program was executed without any issues regarding to the use of the `gdb` program.
Could you run another example than `breakpoint` in `gdb` just to understand its utility? What else can you do with it?

2019-09-19 20:05 UTC, eborghi10 commented on lucas_scheinkerman/Debugging_and_profiling_in_ROS.md
> +```console
Could you explain what do they mean?

2019-09-20 19:01 UTC, LucasJSch commented
# Ready for review

2019-09-20 20:40 UTC, eborghi10 approved these changes
LGTM

2019-09-20 21:31 UTC, eborghi10 commented
Could you put a picture with the launch structure?

2019-09-23 16:32 UTC, LucasJSch commented
# Addressed requested changes.

2019-09-23 16:47 UTC, eborghi10 approved these changes

2019-09-23 16:47 UTC, merged