[WIP] Week4's files added.
ekumenlabs/training_notes_gazebo_ros_2019 pull request #18
Opened 2019-09-25 15:06 UTC by LucasJSch

The description of the 3D model in the '.md' file made is still missing. Same with the 'ROS REP' section.

2019-09-25 17:08 UTC, eborghi10 requested changes

2019-09-25 17:08 UTC, eborghi10 commented on lucas_scheinkerman/Robot_modeling.md
> +## Simulating links as light sensors
Avoid pushing code here. It's fine if you put a link to the PR that adds the code.

2019-10-02 19:06 UTC, LucasJSch commented
# Ready for review

2019-10-06 22:27 UTC, eborghi10 approved these changes
One minor comment, but LGTM.

2019-10-06 22:27 UTC, eborghi10 commented on lucas_scheinkerman/Robot_modeling.md
> +In this week we were assigned to investigate different subject regarding robot moldeing in ROS and Gazebo, and as a final assignment for this week we were asked to model two identical links that simu
Typo: modeling.

2019-10-11 18:54 UTC, merged