Added Ramiro's diff drive summary
ekumenlabs/training_notes_gazebo_ros_2019 pull request #5
Opened 2019-09-05 17:41 UTC by serraramiro1

2019-09-05 17:52 UTC, eborghi10 commented on ramiro_serra/dif_driver_investigation.md
> +# Differential wheeled robots
It's the first time I hear the term "differential wheeled". I always use "differential-drive robot". Anyways, it's okay.

2019-09-05 17:52 UTC, ernestmc approved these changes
lgtm

2019-09-05 17:54 UTC, eborghi10 commented on ramiro_serra/dif_driver_investigation.md
> +###### Differential wheeled robot
Use [headings levels](https://www.markdownguide.org/basic-syntax/#headings) in order.

2019-09-05 17:57 UTC, eborghi10 commented on ramiro_serra/dif_driver_investigation.md
> +To construct a simple model of the constraints that arise from the differential drive, only the distance ![ L](http://planning.cs.uiuc.edu/img83.gif) between the two wheels, and the wheel radius, ![
Equations seem ugly but it's okay.

2019-09-05 17:58 UTC, eborghi10 commented on ramiro_serra/dif_driver_investigation.md
> +To construct a simple model of the constraints that arise from the differential drive, only the distance ![ L](http://planning.cs.uiuc.edu/img83.gif) between the two wheels, and the wheel radius, ![
Could you look in Gazebo which link acts as the body-frame origin as you mentioned in the text?

2019-09-05 18:01 UTC, eborghi10 commented on ramiro_serra/dif_driver_investigation.md
> +If both the wheels are driven in the same direction and speed, the robot will go in a straight line. If both wheels are turned with equal speed in opposite directions, as is clear from the diagram sh
"If both the wheels" -- You can remove "the". It doesn't sound natural.

2019-09-05 18:02 UTC, eborghi10 commented on ramiro_serra/dif_driver_investigation.md
> +Dealing with the displacement and velocities of the two wheels of a differential drive robot is messy. A preferred model is that of a unicycle, where we can think of the robot as having one wheel tha
What does ROS have in terms of velocity messages for the unicycle model?

2019-09-05 18:04 UTC, eborghi10 requested changes
I left some comments, PTAL.

I recommend you to use Visual Studio Code with a Markdown linter to check some styling issues.

2019-09-05 18:54 UTC, serraramiro1 commented
I think I took care of the changes requested, I'll be waiting your feedback. Thank you

2019-09-06 11:47 UTC, eborghi10 requested changes
Another pass done.

2019-09-06 11:47 UTC, eborghi10 commented on ramiro_serra/dif_driver_investigation.md
> +Dealing with the displacement and velocities of the two wheels of a differential drive robot is messy. A preferred model is that of a unicycle, where we can think of the robot as having one wheel tha
In case you addressed this kind of changes in another place, let me know because Github doesn't delete them.

2019-09-06 11:47 UTC, eborghi10 commented on ramiro_serra/dif_driver_investigation.md
> +It's used for example, in *turtlesim*, the simulator we used for the technical challenge:
The repo that we're using uses Twist too. Take a look, where is used.

2019-09-06 11:47 UTC, eborghi10 commented on ramiro_serra/dif_driver_investigation.md
> +### Which link acts as the body-frame origin in Gazebo?
What happens in the case of the robot of our repo?

2019-09-06 17:55 UTC, eborghi10 approved these changes

2019-09-09 20:08 UTC, merged