Notes for Differential Drive and Gazebo
ekumenlabs/training_notes_gazebo_ros_2019 pull request #6
Opened 2019-09-05 19:32 UTC by stevendes

My notes for Diff-Drive and Gazebo

2019-09-06 11:42 UTC, eborghi10 requested changes
First pass done, PTAL.

I recommend you to install Grammarly, a Chrome extension that checks grammatical errors in English.

2019-09-06 11:42 UTC, eborghi10 commented on milner_desvars/diff-drive.md
> +A differential-drive robot is a wheeled robot with two controllable wheels, this wheels only can turn by their axis, so rotation of the robot is accomplished by rotating the wheels in opposite direct
**these** wheels.

- this: singular
- these: plural

2019-09-06 11:42 UTC, eborghi10 commented on milner_desvars/diff-drive.md
> +# how a differential-drive robot works and how to control it
Please add more information about the unicycle model and how that relates to the [Twist](https://docs.ros.org/api/geometry_msgs/html/msg/Twist.html) message.

2019-09-06 11:42 UTC, eborghi10 commented on milner_desvars/diff-drive.md
> +# how a differential-drive robot works and how to control it
That information can be related to what you already wrote.

2019-09-06 11:42 UTC, eborghi10 commented on milner_desvars/gazebo.md
> +When you run Gazebo you are actually running to different executables. In one hand "gzserver" and in the other "gzclient".
You can use `this Markdown style` instead for `gzserver` and `gzclient`.

In order to do that, use this:

```
`this is a one-line code`
```

2019-09-06 11:42 UTC, eborghi10 commented on milner_desvars/gazebo.md
> +The gzserver executable runs the physics update-loop and sensor data generation. This is the core of Gazebo and it can be used independtly of a graphical interphase.
Typo: independently

2019-09-06 11:42 UTC, eborghi10 commented on milner_desvars/gazebo.md
> +The gzserver executable runs the physics update-loop and sensor data generation. This is the core of Gazebo and it can be used independtly of a graphical interphase.
Typo: interface
Check for what "GUI" stands for on Google.

2019-09-06 11:42 UTC, eborghi10 commented on milner_desvars/gazebo.md
> +The gzclient executable runs a QT based user interface. This application provides a nice visualization of simulation, and convenient controls over various simulation properties.
Is it possible to run `gzserver` alone without `gzclient` ?

2019-09-06 11:42 UTC, eborghi10 commented on milner_desvars/gazebo.md
> +## World files
Could you check at least one example of these in the repo?

2019-09-06 11:42 UTC, eborghi10 commented on milner_desvars/gazebo.md
> +## World files
For example, an example of a world file, model file, and plugin. Don't worry if you don't find a plugin.

2019-09-06 11:42 UTC, eborghi10 commented on milner_desvars/gazebo.md
> +GAZEBO_MODE_PATH
Use lists in Markdown and code for the names. More info [here](https://en.support.wordpress.com/markdown-quick-reference/).

2019-09-06 11:42 UTC, eborghi10 commented on milner_desvars/gazebo.md
> +Plugins specified on the command line are loaded fist, then plugins specified in the SDF files are loaded. Some plugins are loaded by the server, such as plugins which affect physics properties, whil
Typo: facilitate

2019-09-06 11:42 UTC, eborghi10 commented on milner_desvars/gazebo.md
> +The communication library currently uses the open source Google Protobuf for the message serialization and boost::ASIO for the transport mechanism. It supports the publish/subscribe communcation para
And what's the difference with ROS?

2019-09-06 11:42 UTC, eborghi10 commented on milner_desvars/gazebo.md
> +Used by almost all subsequent libraries. Acts as the communication and transport mechanism for Gazebo
Missing dot at the end.

2019-09-06 11:42 UTC, eborghi10 commented on milner_desvars/gazebo.md
> +Provides a simple and generic interface to fundamental simulation components, such as rigid bodies, collision shapes, jounts, etc...
Typo: joints.

2019-09-06 11:42 UTC, eborghi10 commented on milner_desvars/gazebo.md
> +Uses OGRE to provide a somple interface for rendering 3D scenes to both the GUI and sensor libraries.
Typo: simple

2019-09-06 11:42 UTC, eborghi10 commented on milner_desvars/gazebo.md
> +Implements all the varoius types of sensors, listens to the world state updates from a physics simulator and produces output specified by the instantianed sensors.
Typo: various

2019-09-06 11:42 UTC, eborghi10 commented on milner_desvars/gazebo.md
> +Implements all the varoius types of sensors, listens to the world state updates from a physics simulator and produces output specified by the instantianed sensors.
Typo: instantiated

2019-09-06 11:42 UTC, eborghi10 commented on milner_desvars/gazebo.md
> +The GUI library uses QT to create graphical widgets for usters to interact with the simulation. The user may control the flow of time by pausing or changing time step size via GUI widgeds
Typo: users

2019-09-06 11:42 UTC, eborghi10 commented on milner_desvars/gazebo.md
> +The GUI library uses QT to create graphical widgets for usters to interact with the simulation. The user may control the flow of time by pausing or changing time step size via GUI widgeds
Missing final dot.

2019-09-06 16:41 UTC, ernestmc reviewed
Left some comments. The Gazebo part is very good but the diff-drive part needs more work to be something useful.

2019-09-06 16:41 UTC, ernestmc commented on milner_desvars/diff-drive.md
> +You can control the robot by controlling the velocity and direction in which the left and right wheels turn, you can use control theory to move the robot by giving the general velocity and direction
The information is not enough to actually control a real robot. Please investigate about how to model the movement and the equations used to obtain the differential speed of each wheel based on the desired linear and angular speeds for the robot.

2019-09-06 16:41 UTC, ernestmc commented on milner_desvars/gazebo.md
> +#Notes
leave a space between the `#` symbol and the text for the title to be correctly interpreted

2019-09-06 16:41 UTC, ernestmc commented on milner_desvars/gazebo.md
> +##Client and server separation
Same comment as above

2019-09-06 16:41 UTC, ernestmc commented on milner_desvars/gazebo.md
> +Contains the elements of the simulation, robots, sensors, etc. This file is formatted using SDF (Simation Description Format), and typically have a .world extension.
Simation --> simulation?

2019-09-06 16:41 UTC, ernestmc commented on milner_desvars/gazebo.md
> +A model file uses the same SDF format as world files, but should only contain a single <model> ... <model>.The purpose of these files is to facilitate model reuse, and simplify world files.
What is this: `<model> ... <model>`

2019-09-06 16:41 UTC, ernestmc commented on milner_desvars/gazebo.md
> +The communication library currently uses the open source Google Protobuf for the message serialization and boost::ASIO for the transport mechanism. It supports the publish/subscribe communcation para
communcation --> communication

2019-09-06 21:27 UTC, eborghi10 approved these changes

2019-09-09 20:02 UTC, ernestmc approved these changes
lgtm

2019-09-09 20:06 UTC, ernestmc commented
@stevendes please squash this PR so we can merge it.

2019-09-09 20:54 UTC, closed without merging