Noteupdate
ekumenlabs/training_notes_gazebo_ros_2019 pull request #7
Opened 2019-09-09 21:46 UTC by stevendes

Trying to update from the branch

2019-09-10 13:17 UTC, ernestmc approved these changes
lgtm

2019-09-10 20:30 UTC, eborghi10 commented
@stevendes when you create a PR add us as reviewers.

2019-09-10 20:36 UTC, eborghi10 requested changes
I left some comments, PTAL.

2019-09-10 20:36 UTC, eborghi10 commented on milner_desvars/diff-drive.md
> +# how a differential-drive robot works and how to control it
Start titles with uppercase letters.

2019-09-10 20:36 UTC, eborghi10 commented on milner_desvars/diff-drive.md
> +R = wheel radius (in meters per radian
Missing ending parenthesis.

2019-09-10 20:36 UTC, eborghi10 commented on milner_desvars/diff-drive.md
> +* Vector3 linear - represents linear part of velocity [m/s]
When you mention code use `this format`. You can do it in this way:

```
`This code will be formatted` and this don't
```

The words I'm referring to are:

- `Vector3`
- `linear.x`
- `Twist`
- ...

2019-09-10 20:36 UTC, eborghi10 commented on milner_desvars/gazebo.md
> +The 'gzserver' executable runs the physics update-loop and sensor data generation. This is the core of Gazebo and it can be used independently of a graphical interface.
Replace single quotes with inverted quotes to use [code formatting](https://help.github.com/en/articles/basic-writing-and-formatting-syntax#quoting-code).

2019-09-10 20:36 UTC, eborghi10 commented on milner_desvars/gazebo.md
> +The 'gzserver' executable runs the physics update-loop and sensor data generation. This is the core of Gazebo and it can be used independently of a graphical interface.
Apply this all over the text.

2019-09-10 20:36 UTC, eborghi10 commented on milner_desvars/gazebo.md
> +*GAZEBO_MODE_PATH
This list is not correctly done. You need a space after the bullet.

2019-09-11 13:08 UTC, ernestmc commented on milner_desvars/ros-notes.md
> +# ROS
This file is for *this* week's assignment. Let's add the new assignment to a different pull-request. Also the rqt image shouldn't go in here.

2019-09-11 14:19 UTC, eborghi10 approved these changes
LGTM!

2019-09-11 15:21 UTC, merged