Added notes.md
ekumenlabs/training_notes_gazebo_ros_2019 pull request #8
Opened 2019-09-10 17:31 UTC by serraramiro1

Added Ramiro's file containing notes for week 2 assignment

2019-09-10 20:37 UTC, eborghi10 commented
@serraramiro1 add us as reviewers. It's a good practice. If not, I think it's a work in progress and I won't take a look.

2019-09-10 20:46 UTC, eborghi10 requested changes
I left some minor comments, PTAL.

2019-09-10 20:46 UTC, eborghi10 commented on ramiro_serra/notes.md
> +After running the docker container, building with catkin, and launching `roslaunch ca_gazebo create_empty_house.launch`, we see gazebo launching and spawning a robot.
The launch file doesn't exist, please check [here](https://github.com/RoboticaUtnFrba/create_autonomy/tree/kinetic-devel/ca_gazebo/launch).

2019-09-10 20:46 UTC, eborghi10 commented on ramiro_serra/notes.md
> +We can see there's 2 cmd_vel topics, let's check which one is being published on:
typo: there're

2019-09-10 20:46 UTC, eborghi10 commented on ramiro_serra/notes.md
> +![teleop_unaligned](media/teleophanging.png)
In this graph you're only showing the nodes. With `rqt_graph` you can see the topics too. Show that output instead.

2019-09-10 20:46 UTC, eborghi10 commented on ramiro_serra/notes.md
> +We can go even further and check with rqt_graph, let's see.
Format the word `rqt_graph`

2019-09-10 20:46 UTC, eborghi10 commented on ramiro_serra/notes.md
> +And, we can check the namespaces, ros doesnt have a command that shows them straight up, but you can list them with `rosnode list | awk -F "/" '{print "/"$2}' | uniq`:
Typo: doesn't

2019-09-10 20:46 UTC, eborghi10 commented on ramiro_serra/notes.md
> +And, we can check the namespaces, ros doesnt have a command that shows them straight up, but you can list them with `rosnode list | awk -F "/" '{print "/"$2}' | uniq`:
Nice command!

2019-09-10 20:46 UTC, eborghi10 commented on ramiro_serra/notes.md
> +So, it seems the multirobot feature Emi added, changes the robot's default namespace; *Dammit, Emi!*
My bad! hahaha 😂

2019-09-10 20:46 UTC, eborghi10 commented on ramiro_serra/notes.md
> +![teleop_aligned](media/teleopaligned.png)
Specify which are the nodes that we should look at or highlight them with some editor.

2019-09-10 20:46 UTC, eborghi10 commented on ramiro_serra/notes.md
> +And, you can go deeper inside the messages, to see how are they composed `rosmsg show geometry_msgs/Twist`:
Off topic: what do you think about the bumper message?

2019-09-11 15:20 UTC, ernestmc reviewed
Looking good!

2019-09-11 15:20 UTC, ernestmc commented on ramiro_serra/notes.md
> +We can see `/key_teleop` node being hanging.
What do you mean by "being hanging"?

2019-09-11 17:53 UTC, eborghi10 requested changes
Another pass done, PTAL.

2019-09-11 17:53 UTC, eborghi10 commented on ramiro_serra/notes.md
> +# Trainee program Week#2 notes
The name of the file is not very descriptive, isn't it?

2019-09-11 17:53 UTC, eborghi10 commented on ramiro_serra/notes.md
> +    /𝗰𝗿𝗲𝗮𝘁𝗲𝟭/𝗰𝗺𝗱_𝘃𝗲𝗹
How did you bold this text? 🤔

2019-09-11 17:53 UTC, eborghi10 commented on ramiro_serra/notes.md
> +We can see `/create1/key_teleop` and `create1/cmd_vel` are connected now! And we can move the turtle, great!
`/create1/cmd_vel` is not a node so it can't be connected to another node. If you see the graph, that's the topic name. Please review.

2019-09-11 20:41 UTC, eborghi10 requested changes
Please, let us know when you finish addressing the changes so we can take a look again. If we don't read email, you won't have your approvals.

2019-09-11 20:41 UTC, eborghi10 commented on ramiro_serra/notes.md
> +We can see `/create1/key_teleop` is now publishing to the correct topic, `/create1/cmd_vel` are connected now! And we can move the turtle, great!
But, which is the other node that is requesting this topic?

2019-09-18 18:33 UTC, serraramiro1 commented
Changes adresssed. Please merge

2019-09-18 18:53 UTC, merged