Created week2 investigation file and added two images
ekumenlabs/training_notes_gazebo_ros_2019 pull request #9
Opened 2019-09-10 18:13 UTC by LucasJSch

2019-09-10 20:47 UTC, eborghi10 commented
@LucasJSch add a minor description to the PR and add us as reviewers, if not, I don't know if it's ready to take a look.

2019-09-10 20:53 UTC, eborghi10 requested changes
Some minor changes, PTAL.

2019-09-10 20:53 UTC, eborghi10 commented on lucas_scheinkerman/ROS_investigation.md
> +The first assignment was to list all the namespaces that exist in the current run of ROS. This was made by listing the present nodes after executing the 'empty_house' simulation and the 'keyboard_tel
Format special words like `awk` and `uniq` with inverted quotes.

2019-09-10 20:53 UTC, eborghi10 commented on lucas_scheinkerman/ROS_investigation.md
> +The first assignment was to list all the namespaces that exist in the current run of ROS. This was made by listing the present nodes after executing the 'empty_house' simulation and the 'keyboard_tel
`empty_house` does not exist.

2019-09-10 20:53 UTC, eborghi10 commented on lucas_scheinkerman/ROS_investigation.md
> +This assignment was completed by executing the command 'rostopic echo /create1/cmd_vel', which corresponds to the topic that has information about the angular and linear velocity of the simulated rob
Could you use inverted quotes instead of single quotes?

2019-09-10 20:53 UTC, eborghi10 commented on lucas_scheinkerman/ROS_investigation.md
> +```console
Please, decrease the amount of information here. It's not necessary to print them all.

2019-09-10 20:53 UTC, eborghi10 commented on lucas_scheinkerman/ROS_investigation.md
> +![rqt_graph without namespace modification](media/screen_without_ns.png)
Replace the images showing the topic names too. And highlight the nodes and topics of interest.

2019-09-10 21:02 UTC, eborghi10 commented
Not related to this PR but you might want to have a different file (other than README.md) for the notes of the 1st week.

2019-09-11 17:24 UTC, eborghi10 commented
Could you move the wk1 docs in a different PR? That change is not related to this one.

2019-09-11 17:25 UTC, eborghi10 approved these changes
Besides moving the changes from wk1 to another PR, LGTM!

2019-09-13 18:09 UTC, LucasJSch commented
# Ready for review

2019-09-13 20:38 UTC, eborghi10 approved these changes
LGTM!

2019-09-18 17:34 UTC, merged